stages:
  load_data:
    cmd: python -m src.nyc_tfp.load_data
    deps:
      - src/nyc_tfp/load_data.py
    outs:
      - data/01_raw/train.csv
    params:
      - paths.dataset_download_path
      - paths.raw_dataset_path


  preprocess:
    cmd: python -m src.nyc_tfp.preprocess
    deps:
      - src/nyc_tfp/preprocess.py
      - data/01_raw/train.csv
    outs:
      - data/02_preprocessed/preprocessed_df.csv
    params:
      - features
      - paths.raw_dataset_path
      - paths.preprocessed_dataset_path

  train:
    cmd: python -m src.nyc_tfp.train_model
    deps:
      - src/nyc_tfp/train_model.py
      - data/02_preprocessed/preprocessed_df.csv
      - params.yaml
    outs:
      - models/model.pkl
      - models/preprocessor.pkl
      - data/train_test_split/X_test.csv
      - data/train_test_split/y_test.csv
      - evaluation/run_id.txt
    params:
      - model
      - features
      - target_feature
      - paths.preprocessed_dataset_path
      - paths.final_dataset_path
      - experiment.name
      - version

  evaluate:
    cmd: python -m src.nyc_tfp.evaluate_model
    deps:
      - src/nyc_tfp/evaluate_model.py
      - models/model.pkl
      - models/preprocessor.pkl
      - data/train_test_split/X_test.csv
      - data/train_test_split/y_test.csv
      - evaluation/run_id.txt
    outs:
      - evaluation/metrics.json


