version: "0.1.0"  # Version of the project
model:
  type: "Lasso"          # 'LinearRegression' or 'Lasso'
  alpha: 0.01            # For Lasso regression

features:
  numeric:
    - pickup_longitude
    - pickup_latitude
    - dropoff_longitude
    - dropoff_latitude
    - trip_distance
    - passenger_count
    - pickup_datetime_year
  boolean:
    - pickup_datetime_is_weekend
    - pickup_datetime_is_late_night
    - pickup_datetime_is_night
    - pickup_datetime_is_early_morning
    - pickup_datetime_is_rush_hour
  cyclic:
    - hour_sin
    - hour_cos
    - dow_sin
    - dow_cos
    - month_sin
    - month_cos
    - doy_sin
    - doy_cos

  # cyclic: []
  categorical: []

target_feature: fare_amount

paths:
  dataset_download_path: data/01_raw
  raw_dataset_path: data/01_raw/train.csv
  preprocessed_dataset_path: data/02_preprocessed/preprocessed_df.csv
  final_dataset_path: data/03_final/final_df.csv
  train_test_split_dir: data/train_test_split
  model_path: models/model.pkl
  preprocessor_path: models/preprocessor.pkl

experiment:
  name: NYC_Taxi_Fare_Pred_Demo
  random_seed: 42
  test_size: 0.2  
  run_type: exp # 'exp' for experiment, 'repro' for reproduction, 'prod' for production
  registered_by: "napsugar"