services:
  - type: web
    name: taxifare-inference-api
    runtime: python          # required property, e.g. python, node, docker
    rootDir: inference
    buildCommand: |
      pip install numpy
      poetry export --without-hashes -f requirements.txt -o requirements.txt
      pip install -r requirements.txt
    startCommand: uvicorn predict:app --host 0.0.0.0 --port $PORT
    plan: free



