services:
  - type: web
    name: taxifare-inference-api
    env: python
    buildCommand: |
      pip install numpy
      poetry export --without-hashes -f requirements.txt -o requirements.txt
      pip install -r requirements.txt
    startCommand: uvicorn inference.predict_using_address:app --host 0.0.0.0 --port $PORT
    plan: free

